# Generated by Django 3.0.4 on 2020-05-21 12:53

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, db_index=True, max_length=128)),
                ('original_filename', models.CharField(blank=True, max_length=128)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('lang', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=191, null=True)),
                ('author', models.CharField(blank=True, max_length=191, null=True)),
                ('content', models.FileField(db_index=True, max_length=191, unique=True, upload_to=app.models._get_upload_path)),
                ('text', models.FileField(max_length=191, upload_to=app.models._text_path)),
                ('html', models.FileField(max_length=191, upload_to=app.models._html_path)),
                ('keyword', models.CharField(blank=True, max_length=191, null=True)),
                ('size_bytes', models.IntegerField(db_index=True, default=0)),
                ('fingerprint', models.FileField(max_length=191, upload_to=app.models._fingerprint_path)),
                ('is_dataset', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('process', 'Process'), ('finished', 'Finished')], default='uploaded', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='DB Insertion Time')),
                ('modified', models.DateTimeField(auto_now=True, help_text='DB Modification Time')),
            ],
            options={
                'permissions': (('add_dataset', 'can add dataset'), ('change_dataset', 'can change dataset'), ('delete_dataset', 'can delete dataset'), ('view_dataset', 'can view dataset')),
            },
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosine', models.FloatField(default=0.0, null=True)),
                ('jaccard', models.FloatField(default=0.0, null=True)),
                ('dice', models.FloatField(default=0.0, null=True)),
                ('manhattan', models.FloatField(default=0.0, null=True)),
                ('minkowski', models.FloatField(default=0.0, null=True)),
                ('mahalanobis', models.FloatField(default=0.0, null=True)),
                ('euclidean', models.FloatField(default=0.0, null=True)),
                ('weighted', models.FloatField(default=0.0, null=True)),
                ('content', models.FileField(blank=True, max_length=191, upload_to=app.models._similarity_result_path)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='DB Insertion Time')),
                ('modified', models.DateTimeField(auto_now=True, help_text='DB Modification Time')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_datasets', to='app.Document')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_documents', to='app.Document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='similarities',
            field=models.ManyToManyField(related_name='similar_to', through='app.Similarity', to='app.Document'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
